-- Database initialization script for Smart Money Tracker

-- Enable UUID extension for unique IDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table 1: Store all alerts generated by the system
CREATE TABLE alerts (
    alert_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL,
    alert_type VARCHAR(30) NOT NULL,
    price NUMERIC(18, 2),
    trade_value NUMERIC(18, 2),
    message TEXT,
    details JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster queries by symbol and time
CREATE INDEX idx_alerts_symbol_time ON alerts(symbol, created_at DESC);
CREATE INDEX idx_alerts_type ON alerts(alert_type);

-- Table 2: Track latest price for each symbol
CREATE TABLE latest_prices (
    symbol VARCHAR(20) PRIMARY KEY,
    price NUMERIC(18, 2) NOT NULL,
    volume_24h NUMERIC(18, 2),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table 3: Store trade statistics for volume calculations
CREATE TABLE trade_stats (
    stat_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL,
    window_start TIMESTAMP NOT NULL,
    window_end TIMESTAMP NOT NULL,
    trade_count INTEGER,
    total_volume NUMERIC(18, 8),
    avg_price NUMERIC(18, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for time-based queries
CREATE INDEX idx_trade_stats_symbol_time ON trade_stats(symbol, window_start DESC);

-- Table 4: Configuration for whale thresholds
CREATE TABLE whale_config (
    symbol VARCHAR(20) PRIMARY KEY,
    whale_threshold NUMERIC(18, 2) DEFAULT 500000,
    large_trade_threshold NUMERIC(18, 2) DEFAULT 100000,
    volume_spike_multiplier NUMERIC(5, 2) DEFAULT 5.0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default configuration for our tracked symbols
INSERT INTO whale_config (symbol) VALUES
    ('BTCUSDT'),
    ('ETHUSDT'),
    ('BNBUSDT');

-- View for quick alert summary
CREATE VIEW alert_summary AS
SELECT
    symbol,
    alert_type,
    COUNT(*) as alert_count,
    MAX(created_at) as last_alert,
    SUM(trade_value) as total_value
FROM alerts
WHERE created_at > CURRENT_TIMESTAMP - INTERVAL '24 hours'
GROUP BY symbol, alert_type
ORDER BY alert_count DESC;

-- Function to clean old data (keep last 30 days)
CREATE OR REPLACE FUNCTION cleanup_old_data() RETURNS void AS $$
BEGIN
    DELETE FROM alerts WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '30 days';
    DELETE FROM trade_stats WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql;

-- Grant permissions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO crypto_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO crypto_admin;